"""
ZK Proof Utilities for Fluxion
════════════════════════════════
Python implementation of the ZK circuit helpers used by the
price_commitment.circom circuit:

  1. FieldElement  — arithmetic modulo the BN128 scalar field.
  2. PoseidonHasher — ZK-friendly hash, verified bit-for-bit compatible
     with circomlib's Poseidon (the same implementation the
     price_commitment.circom circuit uses via `include ".../poseidon.circom"`).
  3. build_commitment — create a hiding Poseidon commitment with a random salt.
  4. ProofInputBuilder — assembles all public + private circuit inputs.
  5. verify_cr_inputs — pure-Python CR check (mirrors circuit constraint #5).

In production the Circom circuit is compiled to a Groth16 prover and the
proofs are verified on-chain by Groth16Verifier.sol.  This module handles
the *input preparation* step that runs client-side (e.g. in a mobile wallet
or a keeper bot) before snarkjs.groth16.fullProve() is called. Because the
circuit re-derives commitCollateral/commitPrice from the private inputs and
constrains them equal to the public commitments, PoseidonHasher here must
produce byte-for-byte identical output to circomlib's Poseidon for a proof
to ever verify — see poseidon_constants.json / the "Poseidon fidelity" note
below for how that's established and kept honest.

Reference for Poseidon constants:
  https://eprint.iacr.org/2019/458
  https://github.com/iden3/circomlibjs
"""

from __future__ import annotations

import json
import secrets
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ─── BN128 scalar field modulus ──────────────────────────────────────────────

SNARK_SCALAR_FIELD: int = (
    21_888_242_871_839_275_222_246_405_745_257_275_088_548_364_400_416_034_343_698_204_186_575_808_495_617
)

# ─── FieldElement ─────────────────────────────────────────────────────────────


class FieldElement:
    """
    An element of GF(SNARK_SCALAR_FIELD).
    Supports +, -, *, ** and automatic modular reduction.
    """

    __slots__ = ("_v",)

    def __init__(self, value: int) -> None:
        self._v = int(value) % SNARK_SCALAR_FIELD

    def __int__(self) -> int:
        return self._v

    def __repr__(self) -> str:
        return f"FieldElement({self._v})"

    def __eq__(self, other: object) -> bool:
        if isinstance(other, FieldElement):
            return self._v == other._v
        if isinstance(other, int):
            return self._v == other % SNARK_SCALAR_FIELD
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._v)

    def __add__(self, other: "FieldElement") -> "FieldElement":
        return FieldElement(self._v + other._v)

    def __sub__(self, other: "FieldElement") -> "FieldElement":
        return FieldElement(self._v - other._v)

    def __mul__(self, other: "FieldElement") -> "FieldElement":
        return FieldElement(self._v * other._v)

    def __pow__(self, exp: int) -> "FieldElement":
        return FieldElement(pow(self._v, exp, SNARK_SCALAR_FIELD))


# ─── Poseidon (circomlib-compatible) ──────────────────────────────────────────
#
# Poseidon fidelity
# ──────────────────
# circomlib's Poseidon uses *different* round constants and a different MDS
# matrix per input width (t = number of inputs + 1), generated by the
# reference Grain-LFSR parameter script, not a small set of constants reused
# across a generic sponge. poseidon_constants.json below was extracted
# directly from the real `circomlibjs` npm package (the same constants the
# circuit's `poseidon.circom` include ultimately compiles from) for widths
# t=2..9 (i.e. 1-8 inputs, covering every arity this module needs), and the
# permutation below follows circomlib's exact reference algorithm (round
# constant added to every state element every round; full S-box in the first
# and last 4 rounds, partial S-box on element 0 only in the middle 57
# rounds; MDS mix each round). This is verified against known-answer vectors
# generated by the real circomlibjs library in
# test_zk_proof_utils.py::TestPoseidonHasher::test_matches_circomlib_reference_vectors
# — if that test passes, this implementation's output is bit-for-bit
# identical to what the actual circuit computes internally.

_POSEIDON_CONSTANTS_PATH = Path(__file__).parent / "data" / "poseidon_constants.json"
with open(_POSEIDON_CONSTANTS_PATH, "r") as _f:
    _POSEIDON_WIDTHS: Dict[str, dict] = json.load(_f)

_POSEIDON_N_ROUNDS_F = 8


class PoseidonHasher:
    """
    Poseidon hash function for the BN128 scalar field, matching circomlib's
    Poseidon template exactly (see "Poseidon fidelity" note above).

    Supports 1-8 inputs, matching every width circomlib's poseidon_constants
    ship parameters for and everything this module's circuit integration
    needs.
    """

    @classmethod
    def hash(cls, inputs: List[FieldElement]) -> FieldElement:
        if not inputs:
            raise ValueError("PoseidonHasher.hash requires at least 1 input")
        t = len(inputs) + 1
        if str(t) not in _POSEIDON_WIDTHS:
            raise ValueError(
                f"Poseidon with {len(inputs)} inputs (width t={t}) is not "
                f"supported; available widths: "
                f"{sorted(int(k) - 1 for k in _POSEIDON_WIDTHS)} inputs"
            )
        width = _POSEIDON_WIDTHS[str(t)]
        c = [int(x) for x in width["C"]]
        m = [[int(x) for x in row] for row in width["M"]]
        n_rounds_f = width["nRoundsF"]
        n_rounds_p = width["nRoundsP"]

        state = [0] + [int(x) % SNARK_SCALAR_FIELD for x in map(int, inputs)]
        total_rounds = n_rounds_f + n_rounds_p
        for r in range(total_rounds):
            state = [(state[i] + c[r * t + i]) % SNARK_SCALAR_FIELD for i in range(t)]
            if r < n_rounds_f // 2 or r >= n_rounds_f // 2 + n_rounds_p:
                state = [pow(a, 5, SNARK_SCALAR_FIELD) for a in state]
            else:
                state[0] = pow(state[0], 5, SNARK_SCALAR_FIELD)
            state = [
                sum(m[i][j] * state[j] for j in range(t)) % SNARK_SCALAR_FIELD
                for i in range(t)
            ]

        return FieldElement(state[0])


# ─── Commitment helper ────────────────────────────────────────────────────────


def build_commitment(
    value: int,
    salt: Optional[int] = None,
) -> Tuple[FieldElement, int]:
    """
    Create a Poseidon hiding commitment: C = Poseidon(value, salt).

    Parameters
    ──────────
    value : int
        The secret integer to commit to (must fit in the scalar field).
    salt  : int | None
        Optional fixed salt (for deterministic tests). When None a
        128-bit cryptographically random salt is generated.

    Returns
    ───────
    (commitment: FieldElement, salt: int)
    """
    if salt is None:
        salt = secrets.randbelow(SNARK_SCALAR_FIELD)

    commitment = PoseidonHasher.hash([FieldElement(value), FieldElement(salt)])
    return commitment, salt


# ─── ProofInputBuilder ────────────────────────────────────────────────────────


@dataclass
class ProofInputBuilder:
    """
    Constructs the full public + private input dict for price_commitment.circom.

    Circuit public inputs:
        commitCollateral, commitPrice, syntheticDebt, minCRbps

    Circuit private inputs:
        collateralAmount, oraclePrice18, saltCollateral, saltPrice
    """

    collateral_amount: int  # raw collateral token units (e.g. USDC ×10^6)
    oracle_price_18: int  # oracle price in 18-decimal USD
    synthetic_debt: int  # outstanding synthetic debt (circuit units)
    min_cr_bps: int  # minimum CR in BPS (e.g. 15000)

    def build(self) -> Dict[str, int]:
        """Return the complete input dict ready for snarkjs."""
        commit_c, salt_c = build_commitment(self.collateral_amount)
        commit_p, salt_p = build_commitment(self.oracle_price_18)

        return {
            # Public
            "commitCollateral": int(commit_c),
            "commitPrice": int(commit_p),
            "syntheticDebt": self.synthetic_debt,
            "minCRbps": self.min_cr_bps,
            # Private
            "collateralAmount": self.collateral_amount,
            "oraclePrice18": self.oracle_price_18,
            "saltCollateral": salt_c,
            "saltPrice": salt_p,
        }


# ─── Pure-Python CR verification (mirrors circuit constraint 5) ───────────────


def verify_cr_inputs(
    collateral_amount: int,
    oracle_price_18: int,
    synthetic_debt: int,
    min_cr_bps: int,
) -> bool:
    """
    Return True iff the position satisfies the minimum collateral ratio.

    This is the Python equivalent of constraints 3–5 in price_commitment.circom:
        collateralUSD = collateral × price / 1e18
        crBps         = collateralUSD × 10000 / syntheticDebt
        crBps >= minCRbps
    """
    if synthetic_debt == 0:
        return True  # No debt → always solvent

    collateral_usd = (collateral_amount * oracle_price_18) // (10**18)
    cr_bps = (collateral_usd * 10_000) // synthetic_debt
    return cr_bps >= min_cr_bps
