name: Fluxion CI/CD

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  lint-infrastructure:
    name: Lint Infrastructure Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint yamllint

      - name: Lint Ansible
        run: |
          cd infrastructure/ansible
          ansible-lint playbooks/main.yml || true

      - name: Lint YAML files
        run: |
          yamllint infrastructure/kubernetes/ infrastructure/ci-cd/ || true

  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: |
          cd infrastructure/terraform
          terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          cd infrastructure/terraform
          terraform init -backend=false

      - name: Terraform Validate
        run: |
          cd infrastructure/terraform
          terraform validate

  validate-kubernetes:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Validate Manifests
        run: |
          cd infrastructure/kubernetes
          for file in base/*.yaml; do
            if [[ -f "$file" && ! "$file" =~ \.example\. ]]; then
              echo "Validating $file..."
              kubectl apply --dry-run=client -f "$file" || echo "Validation failed for $file"
            fi
          done

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy secret scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "./infrastructure"
          scanners: "secret,config"
          exit-code: "1"
          severity: "CRITICAL,HIGH"

      - name: Run Trivy IaC scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "./infrastructure"
          exit-code: "0" # Don't fail build, just report
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  test-application:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f code/backend/requirements.txt ]; then 
            pip install -r code/backend/requirements.txt
          fi

      - name: Run tests
        run: |
          cd code/backend
          python -m pytest --verbose || echo "Tests need configuration"

  build-and-deploy:
    name: Build and Deploy
    needs:
      [
        lint-infrastructure,
        validate-terraform,
        validate-kubernetes,
        security-scan,
        test-application,
      ]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f code/backend/requirements.txt ]; then 
            pip install -r code/backend/requirements.txt
          fi

      - name: Build application
        run: |
          echo "Building application artifacts..."
          # Add build commands here

      - name: Deploy to staging
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploying to staging environment..."
          # Add staging deployment commands here

      - name: Deploy to production
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          echo "Deploying to production environment..."
          # Add production deployment commands here
          # Example: kubectl apply -k infrastructure/kubernetes/overlays/prod/
