apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "fluxion-*"
    editable: false
    jsonData:
      esVersion: "8.0.0"
      logMessageField: message
      logLevelField: level
      timeField: "@timestamp"
    secureJsonData:
      basicAuthPassword: "${ELASTIC_PASSWORD}"
    basicAuth: true
    basicAuthUser: elastic
