// SPDX-License-Identifier: AGPL-3.0
pragma solidity 0.8.19;

/**
 * @title Groth16Verifier
 * @notice On-chain Groth16 verifier for the PriceCommitmentProof circuit.
 *
 * The verification key (vk) below corresponds to the compiled
 * price_commitment.circom circuit.  In production this key is generated by
 * running the Groth16 trusted-setup ceremony and must be committed to the
 * repository alongside the final `final.zkey` artifact.
 *
 * Verification equation (bn128 pairing check):
 *   e(A, B) == e(alpha, beta) · e(vk_x, gamma) · e(C, delta)
 *
 * where:
 *   vk_x = vk_ic[0] + pub[0] * vk_ic[1] + pub[1] * vk_ic[2] + ...
 *
 * Public inputs layout (must match the circom `main` declaration order):
 *   [0] commitCollateral
 *   [1] commitPrice
 *   [2] syntheticDebt
 *   [3] minCRbps
 *
 * References:
 *   Groth16 paper:  https://eprint.iacr.org/2016/260
 *   snarkjs output: https://github.com/iden3/snarkjs
 */
contract Groth16Verifier {
    // ─────────────────────────────────────────────────────────────────────────
    // bn128 field modulus and scalar field modulus
    // ─────────────────────────────────────────────────────────────────────────

    uint256 private constant PRIME_Q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    uint256 private constant SNARK_SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // ─────────────────────────────────────────────────────────────────────────
    // Verification key  (generated by snarkjs after the trusted-setup ceremony)
    // ─────────────────────────────────────────────────────────────────────────

    struct VerifyingKey {
        uint256[2] alpha1; // G1 point
        uint256[2][2] beta2; // G2 point
        uint256[2][2] gamma2; // G2 point
        uint256[2][2] delta2; // G2 point
        uint256[2][] ic; // G1 points  (len = nPublicInputs + 1)
    }

    /**
     * @dev Returns the hard-coded verification key for the
     *      PriceCommitmentProof circuit.
     *
     * These coordinates are illustrative placeholders that match the expected
     * bn128 format.  Replace them with the real ceremony output.
     */
    function _getVk() private pure returns (VerifyingKey memory vk) {
        // alpha1
        vk.alpha1 = [
            0x2d4d9aa7e302d9df41749d5507949d05dbea33fbb16c643b22f599a2be6df2e2,
            0x14bedd503c37ceb061d8ec60209fe345ce89830a19230301f076caff004d1926
        ];
        // beta2
        vk.beta2 = [
            [
                0x0967032fcbf776d1afc985f88877f182d38480a653f2decaa9794cbc3bf3060c,
                0x0e187847ad4c798374d0d6732bf501847dd68bc0e071241e0213bc7fc13db7ab
            ],
            [
                0x304cfbd1e08a704a99f5e847d93f8c3caafddec46b7a0d379da69a4d112346a7,
                0x1739c1b1a457a8c7313123d24d2f9192f896b7c63eea05a9d57f06547ad0cec8
            ]
        ];
        // gamma2
        vk.gamma2 = [
            [
                0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2,
                0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed
            ],
            [
                0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b,
                0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa
            ]
        ];
        // delta2
        vk.delta2 = [
            [
                0x25f83c8b6ab9de74e7da488ef02645c5a16a6652c3c71a15dc37fe3a5dcb7cb1,
                0x22acdedd6308e3bb230d226d16a105295f523a8a02bfc5e8bd2da135ac4c245d
            ],
            [
                0x065bbad92e7c4807d1cf6ec9a03ab4e0243acee2f9fd921df36dca2e65a44e73,
                0x06d302580dc0661002994e7cd3a7f224e7ddc27802777486bf80f40e4ca3cfdb
            ]
        ];
        // ic[0..4]  (1 + 4 public inputs)
        vk.ic = new uint256[2][](5);
        vk.ic[0] = [
            0x22740b9f28574c250c9c2e08e4a6d0e50e7abf599f3d9da63ef4d6b5b8a02afc,
            0x136d9e1ca63e9ff48ffd07bb6f39b4fd0e44ffef8a24ffa21f02ad5c9e5e55cb
        ];
        vk.ic[1] = [
            0x2bd6b0f35484e8df428b08ac88f64741a0c3a11c49c96cdfb0c7e3527acf4987,
            0x0c0c48e476e23faadf66d56d1c4e65e97d90cc2b23e55a3f38c00e0f48be84f1
        ];
        vk.ic[2] = [
            0x1c3ab9ca7e5e3b02b3ec1cf0891be7e53e3f0e7a43b07efe5dffef3f9c3ef9f4,
            0x2fb4c7a86acf98c2f1adf1b6e4f0e6c5a2e73f9e31ded8f9b2d6a3c1f05c8e17
        ];
        vk.ic[3] = [
            0x09e5c1b99c41c8c3d25febd41ab8f76b9e84a4c0d5bde6d5f2a65f3c1e97a24f,
            0x163e4b1a29da9e8e5e5c2c9b4b0e9f7a6e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b
        ];
        vk.ic[4] = [
            0x2a1b3c4d5e6f7089abcdef0123456789abcdef0123456789abcdef0123456789,
            0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
        ];
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Elliptic-curve helpers (bn128)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * @dev Adds two G1 points using the bn128 precompile at address 0x06.
     */
    function _g1Add(
        uint256[2] memory p1,
        uint256[2] memory p2
    ) private view returns (uint256[2] memory r) {
        uint256[4] memory input;
        input[0] = p1[0];
        input[1] = p1[1];
        input[2] = p2[0];
        input[3] = p2[1];
        bool success;
        assembly {
            success := staticcall(gas(), 0x06, input, 0x80, r, 0x40)
        }
        require(success, "G1Add precompile failed");
    }

    /**
     * @dev Multiplies a G1 point by a scalar using the bn128 precompile at 0x07.
     */
    function _g1ScalarMul(
        uint256[2] memory p,
        uint256 s
    ) private view returns (uint256[2] memory r) {
        uint256[3] memory input;
        input[0] = p[0];
        input[1] = p[1];
        input[2] = s;
        bool success;
        assembly {
            success := staticcall(gas(), 0x07, input, 0x60, r, 0x40)
        }
        require(success, "G1ScalarMul precompile failed");
    }

    /**
     * @dev Executes an e(·, ·)^n pairing check using the bn128 precompile
     *      at address 0x08.  Encodes pairs as [G1.x, G1.y, G2.x1, G2.x0,
     *      G2.y1, G2.y0] (the field-extension coordinate order expected by
     *      EIP-197).
     */
    function _pairingCheck(
        uint256[2] memory a1,
        uint256[2][2] memory a2,
        uint256[2] memory b1,
        uint256[2][2] memory b2,
        uint256[2] memory c1,
        uint256[2][2] memory c2,
        uint256[2] memory d1,
        uint256[2][2] memory d2
    ) private view returns (bool) {
        uint256[24] memory input;
        // Pair 1: (A, B)
        input[0] = a1[0];
        input[1] = a1[1];
        input[2] = a2[1][0];
        input[3] = a2[1][1];
        input[4] = a2[0][0];
        input[5] = a2[0][1];
        // Pair 2: (-alpha, beta)
        input[6] = b1[0];
        input[7] = b1[1];
        input[8] = b2[1][0];
        input[9] = b2[1][1];
        input[10] = b2[0][0];
        input[11] = b2[0][1];
        // Pair 3: (-vk_x, gamma)
        input[12] = c1[0];
        input[13] = c1[1];
        input[14] = c2[1][0];
        input[15] = c2[1][1];
        input[16] = c2[0][0];
        input[17] = c2[0][1];
        // Pair 4: (-C, delta)
        input[18] = d1[0];
        input[19] = d1[1];
        input[20] = d2[1][0];
        input[21] = d2[1][1];
        input[22] = d2[0][0];
        input[23] = d2[0][1];

        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(gas(), 0x08, input, 0x300, out, 0x20)
        }
        require(success, "Pairing precompile failed");
        return out[0] == 1;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Public verifier entry point
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * @notice Verifies a Groth16 proof for the PriceCommitmentProof circuit.
     *
     * @param proof  Encoded proof  [A.x, A.y, B.x0, B.x1, B.y0, B.y1, C.x, C.y]
     *               (total 8 × uint256 = 256 bytes)
     * @param input  Public inputs  [commitCollateral, commitPrice,
     *                               syntheticDebt, minCRbps]
     * @return       True iff the proof is valid.
     */
    function verifyProof(
        uint256[8] calldata proof,
        uint256[4] calldata input
    ) external view returns (bool) {
        // Validate all public inputs are in the scalar field
        for (uint256 i; i < 4; ++i) {
            require(input[i] < SNARK_SCALAR_FIELD, "Public input out of field");
        }

        VerifyingKey memory vk = _getVk();

        // Compute vk_x = vk.ic[0] + Σ input[i] * vk.ic[i+1]
        uint256[2] memory vkX = vk.ic[0];
        for (uint256 i; i < 4; ++i) {
            vkX = _g1Add(vkX, _g1ScalarMul(vk.ic[i + 1], input[i]));
        }

        // Extract proof elements
        uint256[2] memory proofA = [proof[0], proof[1]];
        uint256[2][2] memory proofB = [
            [proof[2], proof[3]],
            [proof[4], proof[5]]
        ];
        uint256[2] memory proofC = [proof[6], proof[7]];

        // Negate A for the pairing check  (A' = (A.x, PRIME_Q - A.y))
        uint256[2] memory proofANeg = [
            proofA[0],
            PRIME_Q - (proofA[1] % PRIME_Q)
        ];

        // e(A, B) · e(-alpha, beta) · e(-vk_x, gamma) · e(-C, delta) == 1
        return
            _pairingCheck(
                proofANeg,
                proofB,
                vk.alpha1,
                vk.beta2,
                vkX,
                vk.gamma2,
                proofC,
                vk.delta2
            );
    }
}
